### ISSUE TITLE
Use target domain labels while training?

### ISSUE THREAD

**Issue by YifanXu74** [mgong2/DA_Infer#1]
In code_digits/twin_ac_launch_mnist_mnist.sh, the setting includes:
--source_dataset svhn,mnist_m,mnist,syn_digits --target_dataset svhn.

It seems that target domain svhn's labels are used while training (see line 283 and 354 in train.py). Is there any mistakes?
If there is any implementations to exclude labels of svhn while training, please tell me. Thank you.

**Comment by mgong2** [comment]
We didn't use the target domain labels in the training. You can take a look at lines 84-85 in train_fns.py. We have an index for each domain, and the domain index for the target domain is set to 0. If a domain index is 0, we will remove the labels in the corresponding domain.

**Comment by YifanXu74** [comment]
> We didn't use the target domain labels in the training. You can take a look at lines 84-85 in train_fns.py. We have an index for each domain, and the domain index for the target domain is set to 0. If a domain index is 0, we will remove the labels in the corresponding domain.

Oh I see. Thanks for replying!
