### ISSUE TITLE
 Larger sample than population in syn_digits dataset.

### ISSUE THREAD

**Issue by YifanXu74** [mgong2/DA_Infer#2]
In the digits experiments, 20,000 paired images are sampled from the training set for each dataset. But the syn_digits dataset only contain 10000 samples in SYN_DIGITS_train.pt. Is there any solution？

Error happened in line 80 of code_digits/train.py:
ValueError: Cannot take a larger sample than population when 'replace=False'

**Comment by mgong2** [comment]
Hi Mike,
The SYN_DIGITS_train.pt was wrong. We have uploaded the new dataset, which can be downloaded from the original data link. Please also re-download the code.

Regards,
Mingming

**Comment by YifanXu74** [comment]
> Hi Mike,
> The SYN_DIGITS_train.pt was wrong. We have uploaded the new dataset, which can be downloaded from the original data link. Please also re-download the code.
> 
> Regards,
> Mingming

Thanks. Best wish for your further study:)
